name: build
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30
    env:
      build_type: Release
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: 'recursive'

    - name: Install Skia
      shell: bash
      run: |
        this_dir=$(cygpath "${{ github.workspace }}")
        skia_url=$(source $this_dir/laf/misc/skia-url.sh | xargs)
        skia_file=$(basename $skia_url)
        curl --ssl-revoke-best-effort -L -o "$skia_file" "$skia_url"
        unzip "$skia_file" -d skia

    - uses: aseprite/get-ninja@main

    - uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: x64

    - name: Generating Makefiles
      shell: bash
      run: |
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ env.build_type }} \
          -DENABLE_TESTS=ON \
          -DENABLE_SCRIPTING=on \
          -DENABLE_CCACHE=off \
          -DLAF_BACKEND=skia \
          -DSKIA_DIR=$(realpath skia) \
          -DSKIA_LIBRARY_DIR=$(realpath skia/out/Release-x64)

    - name: Compiling
      shell: bash
      run: |
        cd build && ninja

    # Optional: comment out this step if you just want the build, not the test run
    - name: Running C++ Tests
      shell: bash
      run: |
        cd build && ctest --output-on-failure

    # Optional: comment out this step if you just want the build, not the test run
    - name: Running CLI Tests
      shell: bash
      run: |
        export ASEPRITE=$PWD/build/bin/aseprite
        cd tests
        bash run-tests.sh

    - name: Package build output
      shell: bash
      run: |
        mkdir -p package
        cp build/bin/aseprite.exe package/
        cp -r build/bin/data package/
        cd package
        7z a -tzip ../aseprite-windows-x64.zip *

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: aseprite-windows-x64
        path: aseprite-windows-x64.zip
        retention-days: 14
